services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "sleep 10 && python manage.py runserver 0.0.0.0:8000"
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    volumes:
      - .:/code
    stdin_open: true
    tty: true
    networks:
      - backend

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "sleep 10 && coverage run manage.py test && coverage xml"
    volumes:
      - .:/code
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - backend

networks:
  backend:

volumes:
  db_data:
